name: rust linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt
    - name: Clippy
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo clippy +nightly -- -D warnings
    - name: Build
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo build +nightly --verbose
      
