name: rust linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install rustup and rust nightly
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2020-09-28
    - name: Format
      run: cargo fmt
    - name: Clippy
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo clippy -- -D warnings
    - name: Build
      run: RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo build --verbose
      
